import { PENDING, FULFILLED, REJECTED } from 'redux-promise-middleware';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const FETCH_CATEGORIES_PENDING = `${FETCH_CATEGORIES}_${PENDING}`;
export const FETCH_CATEGORIES_FULFILLED = `${FETCH_CATEGORIES}_${FULFILLED}`;
export const FETCH_CATEGORIES_REJECTED = `${FETCH_CATEGORIES}_${REJECTED}`;
