import { PENDING, FULFILLED, REJECTED } from 'redux-promise-middleware';

export const EDIT_COMMENT = 'EDIT_COMMENT';

export const EDIT_COMMENT_PENDING = `${EDIT_COMMENT}_${PENDING}`;
export const EDIT_COMMENT_FULFILLED = `${EDIT_COMMENT}_${FULFILLED}`;
export const EDIT_COMMENT_REJECTED = `${EDIT_COMMENT}_${REJECTED}`;

export const VOTE_COMMENT = 'VOTE_COMMENT';

export const VOTE_COMMENT_PENDING = `${VOTE_COMMENT}_${PENDING}`;
export const VOTE_COMMENT_FULFILLED = `${VOTE_COMMENT}_${FULFILLED}`;
export const VOTE_COMMENT_REJECTED = `${VOTE_COMMENT}_${REJECTED}`;

export const ADD_COMMENT = 'ADD_COMMENT';

export const ADD_COMMENT_PENDING = `${ADD_COMMENT}_${PENDING}`;
export const ADD_COMMENT_FULFILLED = `${ADD_COMMENT}_${FULFILLED}`;
export const ADD_COMMENT_REJECTED = `${ADD_COMMENT}_${REJECTED}`;

export const DELETE_COMMENT = 'DELETE_COMMENT';

export const DELETE_COMMENT_PENDING = `${DELETE_COMMENT}_${PENDING}`;
export const DELETE_COMMENT_FULFILLED = `${DELETE_COMMENT}_${FULFILLED}`;
export const DELETE_COMMENT_REJECTED = `${DELETE_COMMENT}_${REJECTED}`;
